on: 
  issues:
    types: [opened]
name: Add a new GitHub issue to Project board
jobs:
  add-issues-to-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: add-issues-to-project
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_COLUMN_NAME: Requests/Ideas
        GITHUB_PROJECT_URL: https://github.com/talk2MeGooseman/twitch-interactive-overlay/projects/1
